#!/usr/bin/env python
#Author: MaYaSeVeN
import random, time, urllib2, json

#candidates = [line.strip() for line in open("candidates.txt", 'r')]

print "\n!!! ZOK&ING SHOP Garry'Mod Gift Away !!!\n"

candidatesFromFacebook = ["https://graph.facebook.com/180775518737796/likes?limit=1000&offset=0"]
candidates = []

for candidatesFromPost in candidatesFromFacebook:
  candidatesJson = json.load(urllib2.urlopen(candidatesFromPost))
	for candidatesNumber in range(len(candidatesJson["data"])):
		nameOfCandidate = candidatesJson["data"][candidatesNumber]["name"]
		candidates.append(nameOfCandidate)

for candidate in candidates:		
	print "[-]", candidate
	time.sleep(0.1)
print "\nThe number of candidates = ", len(set(candidates))
print "\nTrying to choose the winners\n"

time.sleep(7)
print "Congratulation to [+]", random.choice(candidates), "\n"
